### ISSUE TITLE
[Q] Must I report browsers with failed test/runner.html?

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#47]
It may be "tests are the first" approach, and current development state is just as is, when some tests are still expectedly failing. So, must I?

**Comment by Kflash** [comment]
I'm on it. There is only issues on client-side, and not server-side. Not directly with the code it seems. Will be fixed soon.

**Comment by gaydenko** [comment]
OK, that is just a state. Thanks for the clarification. So. closing the issue.

**Comment by Kflash** [comment]
The issue have now been solved. It worked on server-side because jsDom seems to be a little different from plain vanila DOM. Anyway. It works for both sides now.

**Comment by gaydenko** [comment]
@Kflash ,  

You are very fast :) I have quickly tried, but still got the errors in browsers. Probably I have missed something (it's really late now - UTC+03). I'll try tomorrow and will report. Thanks!

**Comment by Kflash** [comment]
@gaydenko Still errors? Make sure you download the latest. I changed around 250 code lines!! Ok. Let me know when you can what issues you are facing.

**Comment by gaydenko** [comment]
@Kflash , yes, I still get errors, but much less :) - for some reason `tmp/__spec` wasn't rebuild. Now all is OK in FF, Chrome (all is against 9d81dc5e). Two tests failed in Midori (a browser is based on webkitgtk2):

```
should unset namespaced attributes ‣
expected '' to be null
http://path/trackira/tmp/__spec-build.js:6823:85

should unset a 'xml' namespace attribute ‣
expected '' to be null
http://path/trackira/tmp/__spec-build.js:7203:92
```
And three ones in IE10:
```
attributes
should patch boolean attributes ‣
AssertionError: expected '' to deeply equal 'true'

svg
should unset namespaced attributes ‣
AssertionError: expected '' to be null

XML attributes
should unset a 'xml' namespace attribute ‣
AssertionError: expected '' to be null
```

**Comment by Kflash** [comment]
@gaydenko Sounds interesting. Midori is not one of the most common browsers as far as I know. And often all libraries only supports browsers who is commonly in use among people. 
But for the Midori issue, it is how the browsers are developed. All major browsers see '' as zero, but not this one.  I can see if I can find a workaround for all browsers.

Regarding IE10.  Identical issues here. I will investigate because IE10 are still alive even after Win10 are released.

**Comment by gaydenko** [comment]
@Kflash , agree, Midori isn't one of main player itself. So we are more interested in engine (that is WebKit) spread. Unfortunately, I haven't such information, but I guess at any case it isn't too wide :)

**Comment by Kflash** [comment]
@gaydenko I'm on the issues here now, but more I dig into this I have to say I can't do much. The errors you find in IE10 isn't really and error / issue. It is how the browser works out of the box.

The SVG issue, is like this in the code: ` node.removeAttributeNS( namespace.namespace, namespace.name ); `

As you see, this is vanila javascript. So if you try to workaround it settings it like

` var g = node.removeAttributeNS( namespace.namespace, namespace.name ); '

you will get an `undefined` in return because the value are gone. However, I'm still to figure out a workaround.

**Comment by gaydenko** [comment]
@Kflash , I just formally informed without any dream to adapt something to IE10 :)

**Comment by Kflash** [comment]
@gaydenko Ok. Anyway. It seems hard to handle from this low-level stage because of IE10. Eventuelly this has to be done on a higher level of abstraction. Close this?

**Comment by gaydenko** [comment]
@Kflash , it is already closed, I guess :)

**Comment by Kflash** [comment]
@gaydenko Regarding this closed issue. I'm working on a heavy re-factoring of some of this things now to match the upcoming DOM Living standards. I'm not sure this will solve IE10 issue, but at least everything will become more stable and faster when it comes to direct UI update. Just keep an eye on the repo in the next hours or so.

**Comment by gaydenko** [comment]
@Kflash , thanks, I'm on the way..
